
export const catalog = [
    {
        name: 'lipsense',
        title: 'Lipsense',
        description: 'This is my description. No smudge or budge!',
        mainImage: 'lipsense.png',
        products: [
            'apple_cider.webp',
            'lexie_beary.webp',
            'aussie_rose.webp',
            'luv_it.webp',
            'b_ruby.webp',
            'mauve_ice.webp',
            'beige_champagne.webp',
            'mulled_wine.webp',
            'bella.webp',
            'napa.webp',
            'blackberry.webp',
            'nude.webp',
            'blu_red.webp',
            'nude_pink.webp',
            'bombshell.webp',
            'nutmeg.webp',
            'cappuccino.webp',
            'persimmon.webp',
            'caramel_apple.webp',
            'pink_champagne.webp',
            'caramel_latte.webp',
            'plum.webp',
            'cocoa.webp',
            'plum_pretty.webp',
            'dark_pink.webp',
            'plumeria.webp',
            'dawn_rising.webp',
            'pomegranate.webp',
            'fire_n-ice.webp',
            'praline_rose.webp',
            'fire_opan.webp',
            'precious_topaz.webp',
            'first_love.webp',
            'purple_reign.webp',
            'fleur_de_lisa.webp',
            'razzberry.webp',
            'fly_girl.webp',
            'roseberry.webp',
            'girlfriend.webp',
            'samon.webp',
            'goddess.webp',
            'sassy_z.webp',
            'hazelnut.webp',
            'sheer_berry.webp',
            'heartbreaker.webp',
            'strawberry_shortcake.webp',
            'honey_rose.webp',
            'summer_sunset.webp',
            'kiss_for_a_cause.webp',
            'violette.webp',
            'kiss_me_katie.webp',
            'voilet_volt.webp',
        ],
    },
    {
        name: 'glosses',
        title: 'Gloss',
        description: 'This is my description. No smudge or budge!',
        mainImage: 'cctm.png',
        products: [
            'Bouganvilla.jpg',
            'Opal.jpg',
            'Pink Sand.png',
            'Glossy.jpg',
            'Orchid.jpg',
            'Rose.jpg',
            'Gold Glitter.jpg',
            'Pearl.jpg',
            'Sand.jpg',
            'Matte.jpg',
            'Pink Glitter.jpg',
            'Silver Glitter.jpg',
        ],
    },
    {
        name: 'shadowsense',
        title: 'Shadow sense',
        description: 'Smoky eye lids, ooooh',
        mainImage: 'cctm.png',
        products: [
            'amethyst.webp',
            'pink_opal_shimmer.webp_',
            'candlelight.webp',
            'pink_posey.webp',
            'copper_rose_shimmer.webp',
            'sandstone_pearl.webp',
            'denim.webp',
            'sandstone_pearl_shimmer.webp',
            'garnet.webp',
            'silver_shimmer.webp',
            'granite.webp',
            'silver_violet.webp',
            'moca_java.webp',
            'smoked_topaz.webp',
            'moce_java_shimmer.webp',
            'smoked_topaz_shimmer.webp',
            'mulberry.webp',
            'snow.webp',
            'onyx.webp',
            'whisper_pink.webp',
            'pink_frost.webp',
        ],
    },
];
