
export const catalog = [
    {
        name: 'lipsense',
        title: 'LipSense',
        description: 'Lip color that is waterproof, smudge proof, budge proof, kiss proof AND it lasts up to 18 hours? Yes, please!',
        price: 25,
        mainImageText: 'LipSense',
        mainImage: 'lipsense.jpg',
        products: [
            'apple_cider.jpg',
            'lexie_beary.jpg',
            'aussie_rose.jpg',
            'luv_it.jpg',
            'b_ruby.jpg',
            'mauve_ice.jpg',
            'beige_champagne.jpg',
            'mulled_wine.jpg',
            'bella.jpg',
            'napa.jpg',
            'blackberry.jpg',
            'nude.jpg',
            'blu_red.jpg',
            'nude_pink.jpg',
            'bombshell.jpg',
            'nutmeg.jpg',
            'cappuccino.jpg',
            'persimmon.jpg',
            'caramel_apple.jpg',
            'pink_champagne.jpg',
            'caramel_latte.jpg',
            'plum.jpg',
            'cocoa.jpg',
            'plum_pretty.jpg',
            'dark_pink.jpg',
            'plumeria.jpg',
            'dawn_rising.jpg',
            'pomegranate.jpg',
            'fire_n-ice.jpg',
            'praline_rose.jpg',
            'fire_opal.jpg',
            'precious_topaz.jpg',
            'first_love.jpg',
            'purple_reign.jpg',
            'fleur_de_lisa.jpg',
            'razzberry.jpg',
            'fly_girl.jpg',
            'roseberry.jpg',
            'samon.jpg',
            'goddess.jpg',
            'sassy_z.jpg',
            'hazelnut.jpg',
            'sheer_berry.jpg',
            'heartbreaker.jpg',
            'strawberry_shortcake.jpg',
            'honey_rose.jpg',
            'summer_sunset.jpg',
            'kiss_for_a_cause.jpg',
            'violette.jpg',
            'kiss_me_katie.jpg',
            'voilet_volt.jpg',
        ],
    },
    {
        name: 'gloss',
        title: 'Gloss',
        description: 'These beautiful glosses will add deep moisture on top of LipSense® lip color or on bare lips. Gloss helps seal in our amazing LipSense® and improve the longevity of the color.',
        price: 20,
        mainImageText: 'Gloss',
        mainImage: 'gloss.jpg',
        products: [
            'Bouganvilla.jpg',
            'Opal.jpg',
            'Pink Sand.jpg',
            'Glossy.jpg',
            'Orchid.jpg',
            'Rose.jpg',
            'Gold Glitter.jpg',
            'Pearl.jpg',
            'Sand.jpg',
            'Matte.jpg',
            'Pink Glitter.jpg',
            'Silver Glitter.jpg',
        ],
    },
    {
        name: 'shadowsense',
        title: 'ShadowSense',
        description: 'Experience gorgeous, long-lasting eye shadow shades. This creme to powder formula can be blended to create incredible and unique looks.',
        price: 22,
        mainImageText: 'ShadowSense',
        mainImage: 'shadowsense.jpg',
        products: [
            'amethyst.jpg',
            'pink_opal_shimmer.jpg',
            'candlelight.jpg',
            'pink_posey.jpg',
            'copper_rose_shimmer.jpg',
            'sandstone_pearl.jpg',
            'denim.jpg',
            'sandstone_pearl_shimmer.jpg',
            'garnet.jpg',
            'silver_shimmer.jpg',
            'granite.jpg',
            'silver_violet.jpg',
            'moca_java.jpg',
            'smoked_topaz.jpg',
            'moce_java_shimmer.jpg',
            'smoked_topaz_shimmer.jpg',
            'mulberry.jpg',
            'snow.jpg',
            'onyx.jpg',
            'whisper_pink.jpg',
            'pink_frost.jpg',
            'rustic_brown.jpg',
        ],
    },
    {
        name: 'lashsense',
        title: 'LashSense and Liner',
        description: 'Make those eyes pop with our highly pigmented mascara that curls, lengthens, and strengthens your lashes to volumized perfection!',
        mainImageText: 'LashSense and Liner',
        mainImage: 'mascara.jpg',
        products: [
            'Black Brown Liquid.jpg',
            'Brown Liner.jpg',
            'Primer.jpg',
            'Black Liner.jpg',
            'Gold Eye liner.jpg',
            'Waterproof.jpg',
            'Black Liquid.jpg',
            'Navy Eye Liner.jpg',
            'non-waterproof.jpg',
        ],
    },
    {
        name: 'cctm',
        title: 'cctm',
        lowercase: true,
        description: 'Are you ready for magic in a bottle? Enjoy a natural sheer coverage, color correcting benefits and skin protection in one easy step! CCTM works to counteract redness and decrease sun and age spots while offering a shield of sun protection!',
        price: 45,
        mainImageText: 'Color Correcting Tinted Moisturizer',
        mainImage: 'cctm.jpg',
        products: [
            'CCTM.jpg',
        ],
    },
    {
        name: 'makesense',
        title: 'MakeSense Foundation',
        description: 'Non-smearing, long-lasting, full coverage in a unique formula that gives a beautiful matte finish, skin care, and sun protection.',
        price: 50,
        mainImageText: 'MakeSense Foundation',
        mainImage: 'foundation.jpg',
        products: [
            'Adobe.jpg',
            'Creme Beige.jpg',
            'Pearlizer.jpg',
            'Almond.jpg',
            'Deep Caramel.jpg',
            'Porcelain.jpg',
            'Beige Chiffon.jpg',
            'Dewy.jpg',
            'Suede.jpg',
            'Cafe Au Lait.jpg',
            'Fawn.jpg',
            'Tan.jpg',
            'Cinnamon.jpg',
            'Golden Tan.jpg',
            'Truffle.jpg',
            'Coffee.jpg',
            'Ivory.jpg',
        ],
    },
    {
        name: 'blushsense',
        title: 'BlushSense',
        description: 'This velvety cream formula will help you achieve the perfect touch of natural-looking, long-lasting color. Define, highlight and contour while nourishing your skin!',
        price: 30,
        mainImageText: 'BlushSense',
        mainImage: 'blushsense.jpg',
        products: [
            'Bronze.jpg',
            'Pink Berry.jpg',
            'Toasted Rose.jpg',
            'Cherry.jpg',
            'Pouty Pink.jpg',
            'Chocolate Cherry.jpg',
            'Terra Cotta.jpg',
        ],
    },
    {
        name: 'concealer',
        title: 'Concealer',
        description: 'Creamy, long-lasting formula that nourishes your skin while providing perfect coverage for that flawless finish!',
        price: 25,
        mainImageText: 'Concealer',
        mainImage: 'concealer.jpg',
        products: [
            'Deep.jpg',
            'Light.jpg',
            'Medium.jpg',
            'Green.jpg',
            'Medium.jpeg',
            'White.jpg',
        ],
    },
    {
        name: 'powder',
        title: 'Loose Powders',
        description: 'Warmth and glow on-the-go meets effortless application with finely-milled, light powder with breathable finish in an all-in-one dispensing brush!',
        price: 50,
        mainImageText: 'Loose Powders',
        mainImage: 'powder.jpg',
        products: [
            'Bronze Dust.jpg',
            'Natural.jpg',
            'Silver Rose.jpg',
        ],
    },
];
