export const limitedEditions = [
    {
        title: "Pretty N' Pink ShadowSense Collection",
        description: "<p>This Limited Edition Collection includes:</p><ul><li>Ballet Slipper ShadowSense</li><li>Pretty N' Pink ShadowSense</li><li>Sweet Rose Shimmer ShadowSense</li><li>Pink Organza Bag – Free!</li></ul><p>*All colors can be purchased individually for $22</p>",
        imgName: 'pretty_n_pink',
        images: [ 'pretty_n_pink', 'description', 'ballet_slipper', 'pretty_n_pink_shadowsense', 'sweet_rose_shimmer' ],
        price: 66,
    },
    {
        title: 'Mystical Gloss Duo Collection',
        description: '<p>This Limited Edition Collection includes:</p><ul><li>Mystic Berry Gloss</li><li>Pink Fortune Gloss</li><li>Turquoise Organza Bag – Free!</li></ul><p>*Both colors can be purchased individually for $20</p>',
        imgName: 'mystical_gloss',
        images: [ 'mystical_gloss', 'description', 'mystic_berry', 'pink_fortune' ],
        price: 40,
    },
    {
        title: 'Sunset Skies LipSense Collection',
        description: '<p>This Limited Edition Collection includes:</p><ul><li>Berry LipSense</li><li>Sheer Red LipSense</li><li>Amber Spice LipSense</li><li>Rose Gloss - Free!</li><li>Mauve Metallic Bag – Free!</li></ul><p>*All colors can be purchased individually for $25</p>',
        imgName: 'sunset_skies_lipsense',
        images: [ 'sunset_skies_lipsense', 'description', 'berry', 'sheer_red', 'amber_spice' ],
        price: 75,
        value: 100,
    },
    {
        title: 'Sunset Skies ShadowSense Collection',
        description: '<p>This Limited Edition Collection includes:</p><ul><li>Rust ShadowSense</li><li>Plum Berry ShadowSense</li><li>Twilight Shimmer ShadowSense</li><li>Mauve Metallic Bag – Free!</li></ul><p>*All colors can be purchased individually for $22</p>',
        imgName: 'sunset_skies_shadowsense',
        images: [ 'sunset_skies_shadowsense', 'description', 'rust', 'plum_berry', 'twilight_shimmer' ],
        price: 66,
    },
    {
        title: 'Big City ShadowSense Collection',
        description: '<p>This Limited Edition Collection includes:</p><ul><li>Brownstone Shimmer ShadowSense</li><li>Brights Lights Glitter ShadowSense</li><li>Burgundy ShadowSense</li><li>Burgundy Metallic Bag – Free!</li></ul><p>*All colors can be purchased individually for $22</p>',
        imgName: 'big_city_shadowsense',
        images: [ 'big_city_shadowsense', 'description', 'brownstone_shimmer', 'bright_lights_glitter', 'burgundy' ],
        price: 66,
    },
    {
        title: 'Big City LipSense Collection',
        description: '<p>This Limited Edition Collection includes:</p><ul><li>Big Apple LipSense ($25)</li><li>Broadway Bronze LipSense ($25)</li><li>Manhattan Mauve LipSense ($25)</li><li>Brooklyn Gloss ($20)</li><li>Ooops! Lip Color Remover – Free!</li><li>Burgundy Metallic Bag – Free!</li></ul><p>*All colors can be purchased individually</p>',
        imgName: 'big_city',
        images: [ 'big_city', 'description', 'big_apple', 'broadway_bronze', 'manhattan_mauve', 'brooklyn' ],
        price: 95,
        value: 110,
    },
    {
        title: 'Color Surge ShadowSense Collection',
        description: '<p>This Limited Edition Collection includes:</p><ul><li>Fiery Coral Shimmer ShadowSense</li><li>Plasma Pink ShadowSense</li><li>Amped Up Orange ShadowSense</li><li>Neon Green Shimmer ShadowSense</li><li>Neon Green Bag – Free!</li></ul><p>*All colors can be purchased individually for $22</p>',
        imgName: 'color_surge',
        images: [ 'color_surge', 'fiery_coral_shimmer', 'plasma_pink', 'amped_up_orange', 'neon_green_shimmer' ],
        price: 88,
    },
    {
        title: 'California Dreamin’ LipSense Collection',
        description: '<p>This Limited Edition Collection includes:</p><ul><li>Sunshine LipSense ($25)</li><li>Boysenberry LipSense ($25)</li><li>Citrus Grove Gloss ($20)</li><li>Ooops! Lip Color Remover – Free!</li><li>Mint Glitter Bag – Free!</li></ul><p>*All colors can be purchased individually</p>',
        imgName: 'california_dreaming',
        images: [ 'california_dreaming', 'description', 'sunshine', 'boysenberry', 'citrus_grove' ],
        price: 70,
        value: 85,
    },
    {
        title: 'California Dreamin’ ShadowSense Collection',
        description: '<p>This Limited Edition Collection includes:</p><ul><li>Desert Rose ShadowSense</li><li>Sunbaked Shimmer ShadowSense</li><li>Sea Breeze Shimmer ShadowSense</li><li>Mint Glitter Bag – Free!</li></ul><p>*All colors can be purchased individually for $22</p>',
        imgName: 'cd_shadowsense',
        images: [ 'cd_shadowsense', 'description', 'desert_rose', 'sunbaked_shimmer', 'sea_breeze_shimmer' ],
        price: 66,
    },
    {
        title: 'Satin Matte Nude Gloss Collection',
        description: '<p>This Limited Edition Collection includes:</p><ul><li>Bella Matte Gloss</li><li>Cream Matte Gloss</li><li>Hazel Matte Gloss</li><li>Praline Matte Gloss</li><li>Brown Glitter Bag – Free!</li></ul><p>*All colors can be purchased individually for $20</p>',
        imgName: 'satin_matte',
        images: [ 'satin_matte', 'description', 'bella_matte', 'cream_matte', 'hazel_matte', 'praline_matte' ],
        price: 80,
    },
    {
        title: 'In Bloom Collection',
        description: '<p>This Limited Edition Collection includes:</p><ul><li>Red Lantern LipSense ($25)</li><li>Cherry Blossom Gloss ($20)</li><li>Moonbeam Shimmer ShadowSense ($22)</li><li>Ooops! Lip Color Remover – Free!</li><li>Metallic White Bag – Free!</li></ul><p>*All items can be purchased individually</p>',
        imgName: 'in_bloom',
        images: [ 'in_bloom', 'red_lantern', 'cherry_blossom', 'moonbeam_shimmer' ],
        price: 67,
        value: 82,
    },
    {
        title: 'Mini Pearlizer Get Glowing Collection',
        description: '<p>This Limited Edition Collection includes:</p><ul><li>Moonstone Mini Pearlizer</li><li>Firefly Mini Pearlizer</li><li>Ember Mini Pearlizer</li><li>Clear Holographic Bag – Free!</li></ul><p>*All colors can be purchased individually for $30</p>',
        imgName: 'get_glowing',
        images: [ 'get_glowing', 'moonstone', 'firefly', 'ember' ],
        price: 90,
    },
];
